<a href="https://colab.research.google.com/github/rohankumar1234590/Sale_Prediction_from_Existing_Customer/blob/main/Sale_Prediction_from_Existing_Customer.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Sale Prediction From Existing Customer


###Importing Libraries

In [ ]:
import pandas as pd #usefull for loading the dataset
import numpy as np #to perform array (help in mathematical operations )


####Choose Dataset from local Directory

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving sales - Sheet1.csv to sales - Sheet1.csv


#####Load the Dataset

In [ ]:
dataset= pd.read_csv('sales - Sheet1.csv')
print(dataset)

    Age   Salary   Status
0     18    82000       0
1     29    80000       0
2     47    25000       1
3     45    26000       1
4     46    28000       1
5     48    27000       1
6     45    25000       1
7     46    22000       1
8     47    23000       1
9     49    22000       1
10    47    28000       1
11    29    40000       1
12    32    41000       0
13    31   132000       0
14    27    27000       0
15    21    70000       1
16    26    50000       0
17    27    40000       0
18    35    60000       0
19    33    70000       0


#####Summarize the dataset

In [ ]:
print(dataset.shape)
print(dataset.head(5))

(20, 3)
   Age   Salary   Status
0    18    82000       0
1    29    80000       0
2    47    25000       1
3    45    26000       1
4    46    28000       1


######Segregate dataset into X(Inputn/dependent variable) & Y(Output/Dependent Variable)



In [ ]:
X =dataset.iloc[:,:-1].values
X

array([[    18,  82000],
       [    29,  80000],
       [    47,  25000],
       [    45,  26000],
       [    46,  28000],
       [    48,  27000],
       [    45,  25000],
       [    46,  22000],
       [    47,  23000],
       [    49,  22000],
       [    47,  28000],
       [    29,  40000],
       [    32,  41000],
       [    31, 132000],
       [    27,  27000],
       [    21,  70000],
       [    26,  50000],
       [    27,  40000],
       [    35,  60000],
       [    33,  70000]])

In [ ]:
Y =dataset.iloc[:,-1].values
Y

array([0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0])

####Spliting dataset into train & test

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test ,Y_train , Y_test = train_test_split(X, Y, test_size=0.25, random_state= 0)

####Feature Scaling
we scale our data to make all feature contribute equally to the result
Fit_Transform-fit method is calculating the mean and variance of each of the features present in our data
Transform - Transform mentod is transforming all the features using respective mean and variance
We want to test our data to be completely new and a Surprise set for our model

In [ ]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()#standard scaling method
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)
print(X_train)

[[-0.8274927  -0.13014309]
 [ 0.865106   -0.64386582]
 [-0.45135965  3.02068966]
 [ 0.95913926 -0.54112128]
 [ 1.05317252 -0.64386582]
 [ 1.14720578 -0.57536946]
 [-0.8274927  -0.57536946]
 [ 1.24123905 -0.74661037]
 [ 0.95913926 -0.74661037]
 [-0.92152596  0.21233873]
 [-0.63942618 -0.13014309]
 [ 0.865106   -0.60961764]
 [-1.67379205  1.30828056]
 [-1.39169226  0.89730237]
 [-0.35732639 -0.09589491]]


###Training

In [ ]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression(random_state = 0)
model.fit(X_train,Y_train)

LogisticRegression(random_state=0)

###Predicting, Wheather new customer with Age & Salary will Buy or Not

In [ ]:
age = int(input("Enter the New Customer's Age : "))
sal = int(input("Enter the New Customer's Salary : "))
newCust = [[age,sal]]
result= model.predict(sc.transform(newCust))
print(result)
if result == 1:
  print("Customer will buy")
else:
  print("customer won't buy ")

Enter the New Customer's Age : 18
Enter the New Customer's Salary : 82000
[0]
customer won't buy 


####Prediction for all Test Data

In [ ]:
Y_pred= model.predict(X_test)
print(np.concatenate((Y_pred.reshape(len(Y_pred),1), Y_test.reshape(len(Y_test),1)),1))

[[1 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]]


###Accuracy 

In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm=confusion_matrix(Y_test, Y_pred)

print("Confusion Matrix")
print(cm)

print("Accuracy of the Model : {0}%".format(accuracy_score(Y_test, Y_pred)*100))

Confusion Matrix
[[2 1]
 [0 2]]
Accuracy of the Model : 80.0%
